version: '3'

services:

    app:
        build: ./php
        image: php:8.1.16-fpm
        container_name: tms_php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: ${APP_PATH_CONTAINER}
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./../app/storage:/var/www/html/storage

    webserver:
        image: nginx:alpine
        container_name: tms_nginx
        restart: unless-stopped
        tty: true
        ports:
            - 7777:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ${APP_PATH_HOST}/public:${APP_PATH_CONTAINER}/public
            - ./../app/storage:/var/www/html/storage

    db:
        image: mariadb
        container_name: tms_mysql
        command: "--default-authentication-plugin=mysql_native_password"
        restart: unless-stopped
        tty: true
        ports:
            - 7776:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        volumes:
            - ./mysql/data:/var/lib/mysql/

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: tms_phpmadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 7760:80
